# Generated by Django 6.0.2 on 2026-02-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_alter_posts_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=30, null=True),
        ),
    ]
