# Generated by Django 6.0.2 on 2026-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0011_post_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.TextField(blank=True, max_length=2200, null=True),
        ),
    ]
